[package]
name = "uno"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
groqu = "0.1.2"
rand = "0.9.1"
tokio = { version = "1.45.1", features = ["rt", "rt-multi-thread", "macros"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
